apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicimg-deployment
  namespace: dineshtele
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basicimg
  template:
    metadata:
      labels:
        app: basicimg
    spec:
      containers:
      - name: basicimg
        image: hypervision201/basicimg:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basicimg-service
  namespace: dineshtele
spec:
  selector:
    app: basicimg
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
